require('configs/base')
require('plugins/theme')
require('plugins/lualine-nvim')
require('plugins/gitsigns')
require('plugins/cmp')
require('plugins/lsp')
require('plugins/codecompanion')
require('plugins/hardtime')
require('nvim-autopairs').setup({})
require('render-markdown')
require('csvview').setup({})
require('hunk').setup({})
require('amp').setup({ auto_start = true, log_level = 'info' })
