#!/usr/bin/env ruby

def alert(message)
  `notify-send "#{message}" -u critical`
end

def get_string(options, label)
  options_string = options.join("\n")
  selected = `echo "#{options_string}" | tofi --prompt-text "#{label}: "`.chomp
  return selected if options.include?(selected)

  error = "#{label} not found: #{selected}."
  alert(error)
  fail(error)
end

device_id = nil
devices = `ykman list`.split("\n")

case devices.size
when 0
  error_message = ["No security key found.", "Insert one and try again."]
  alert(error_message.join("\n"))
  fail error_message.join(" ")
when 1
  device_id = devices[0].split(/\s/).last
else
  selected_device = get_string(devices, "Key")
  device_id = selected_device.split(/\s/).last
end

accounts = `ykman --device #{device_id} oath accounts list`.split("\n")
account = get_string(accounts, "Account")
`ykman --device #{device_id} oath accounts code #{account} | awk '{printf $2}' | wl-copy`
